version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: "development"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=root
      - MONGO_PASSWORD=root
      - SESSION_SECRET=OHqM2MmrwzPRD3stoEbVOETY2zVnJtUqd54
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
